### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [NathanGE/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by NathanGE** [comment]
Thanks Ken! I added the meta tag to the head of my app/views/layouts/application.html.erb - 
<meta name="viewport" content="width=device-width, initial-scale=1">
I think that did the trick.

**Comment by NathanGE** [comment]
Thanks Ken! I added the meta tag to my app/views/layouts/application.html.erb file and I think it did the trick.

**Comment by kenmazaika** [comment]
Looks perfect, Nathan.  Thumbs up.  :+1:
